version: "2"
services:
  mysqldb:
    image: mysql:8
    container_name: triagildatabase
    restart: unless-stopped
    env_file: ./.env
    environment:
        - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
        - MYSQL_DATABASE=$DATABASE_NAME
        - MYSQL_TCP_PORT=$DATABASE_PORT
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./src/data:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - mysqldb
    container_name: triagilapp
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/triagilapp
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
    expose:
      - "3003"
    ports:
      - "3003:3003"
    stdin_open: true
    tty: true
